<html>
    <head>
        <title>Uso de Liberias y Funciones</title>
    </head>
    <body>
        <?php
        function cabeceraPagina(){
            
        
        ?>
        <FONT SIZE="+1">Esta cabecera estará en todas tus paginas</FONT><br>
        <hr>
        <?php
        }
        function piePagina(){
            ?>
        
        <hr>
        <FONT SIZE="-1">Este es el pie de página.</FONT><BR>
        AUTOR JOAQUIN GARCIA
        <?php
        
        }
        ?>
    </body>
</html>